# Generated by Django 4.2.10 on 2024-05-08 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='courses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_id', models.CharField(max_length=6)),
                ('cname', models.CharField(max_length=20)),
                ('dept', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='gpa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('s_id', models.IntegerField()),
                ('final_score', models.IntegerField()),
                ('gpa', models.DecimalField(decimal_places=2, max_digits=4)),
            ],
        ),
        migrations.CreateModel(
            name='marks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('s_id', models.IntegerField()),
                ('course_id', models.CharField(max_length=6)),
                ('cla1_marks', models.IntegerField()),
                ('cla2_marks', models.IntegerField()),
                ('mid1_marks', models.IntegerField()),
                ('mid2_marks', models.IntegerField()),
                ('endsem_marks', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='results',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('s_id', models.IntegerField()),
                ('course_id', models.CharField(max_length=6)),
                ('percentage', models.IntegerField()),
                ('total_marks', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='st_map_details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('s_id', models.IntegerField(unique=True)),
                ('t_list', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Student_details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(max_length=40)),
                ('lname', models.CharField(max_length=40)),
                ('reg_no', models.CharField(max_length=55, unique=True)),
                ('dept', models.CharField(max_length=10)),
                ('pw', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='teacher_details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(max_length=40)),
                ('lname', models.CharField(max_length=40)),
                ('f_code', models.IntegerField(unique=True)),
                ('subject', models.CharField(max_length=20)),
                ('dept', models.CharField(max_length=20)),
                ('username', models.CharField(max_length=20, unique=True)),
                ('pw', models.CharField(max_length=40)),
            ],
        ),
    ]
